apiVersion: apps/v1
kind: Deployment
metadata:
  name: star-burger
  labels:
    app: star-burger
spec:
  selector:
    matchLabels:
      project: star-burger
  template:
    metadata:
      labels:
        project: star-burger
    spec:
      containers:
        - name: django
          image: djangoapp
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: env-configs

---
apiVersion: v1
kind: Service
metadata:
  name: django-app
  labels:
    env: prod
    owner: JuliaKendo
spec:
  selector:
    project: star-burger
  ports:
    - name: django
      protocol: TCP
      port: 80

