
version: "3"

services:

  web:
    environment:
      DATABASE_URL: ${WEB_DATABASE_URL-postgres://postgres:12345@192.168.1.87:6767/test}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS-127.0.0.1,0.0.0.0,192.168.1.87,85.175.101.149,localhost}
