apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  SECRET_KEY: 12345
  DEBUG: False
  ALLOWED_HOSTS: *
  DATABASE_URL: postgres://postgres:12345@85.175.101.149:6767/test
